### ISSUE TITLE
Is there a way to use this library and keep the console logs sane

### ISSUE THREAD

**Issue by rlindner81** [SAP/cf-java-logging-support#28]
Our project is using logback and we are trying to improve the Kibana logging for our CF application. We have bound the usual `application-logs` service, but out-of-the-box the log level of our Java server logs is not properly recognized and stack traces get logged as multiple records.

Now when I follow the configuration here:
```xml
    <appender name="STDOUT-JSON" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="com.sap.hcp.cf.logback.encoder.JsonEncoder"/>
    </appender>
```
I see this JSON log on the console always, which is not acceptable for me. I actually don't want to change my console logs in any way.

Do you provide an appender that writes into `logstash` directly?

Like
https://github.com/logstash/logstash-logback-encoder
> net.logstash.logback.appender.LogstashSocketAppender
> net.logstash.logback.appender.LogstashTcpSocketAppender

Or even populate logstash from files persisted by the application:
https://www.baeldung.com/java-application-logs-to-elastic-stack

**Comment by KarstenSchnitter** [comment]
The default way of log shipment in Cloud Foundry is to collect standard out and standard err stream of the application. This is done by the Metron agent running on every Diego cell where the applications are executed. This creates a stream of log messages, that is shipped by the Loggregator component of Cloud Foundry, of which Metron is the ingestion point. By creating a service binding to the Application Logging Service, we subscribe to the logging stream of your application and ingest it to Elasticsearch, so that you can search for your logs using Kibana. The decision of using standard out and standard err or in other words the console is one of the opinionated choices within Cloud Foundry. We do not support other ways of log shipment. Such a feature would need its own authentication and connectivity implementations and is therefore out of our scope.

**Comment by rlindner81** [comment]
Thanks for the clarification. I understand that capturing the basic console logs through loggregator leaves you no other choice than starting to change the format of those console logs and making them easier to use for Kibana and harder to use in other contexts.

I guess the solution I imagined is more in the spirit of some other cf services where the binding gives you access to a server and the application decides what is sent there and in what format. Either way, you answered my question.
